### PR TITLE
fix windows build

### LINKED ISSUE #2: Project does not compile on Windows
build failing in CI on Windows as of 6ab4c238b2237db1a5f987db08fbf53c9c761a7c.

### PR DESCRIPTION
**Pull request by DecibelChat**
resolves #2

### CODE REVIEW

File: src/MessageType.hpp [hunk 1]
```diff
@@ -10,13 +10,13 @@ namespace websocket_server
     SDP,
     CANDIDATE,
     SERVER,
-    DELETE
+    REMOVE_CLIENT // note: 'DELETE' is overriden by a define in Windows system files.
```
Comment (DecibelChat) [inline src/MessageType.hpp]: it probably doesn't make sense to add a message type for this purpose anyways

Comment (DecibelChat) [reply src/MessageType.hpp]: removed `DELETE` from `MessageType`. Will use `Server` type instead.

File: src/server.cpp [hunk 2]
```diff
@@ -160,13 +160,15 @@ namespace websocket_server
...
   {
-    constexpr auto uuid_key = peer_id_key;
+    constexpr auto uuid_key       = peer_id_key;
+    constexpr auto delete_message = "delete";
 
     const auto &client      = client_mapping_.at(handle);
     const auto &client_uuid = client.id();
     const auto &room_id     = client.room();
 
-    json message = {{uuid_key}, {client_uuid}, {message_type_key, message_type_to_string.at(MessageType::DELETE)}};
```
Comment (DecibelChat) [inline src/server.cpp:169]: fyi, this was broken: `{uuid_key}, {client_uuid}` --> `{uuid_key, client_uuid}`
